version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - web
    restart: always
  web:
    build: .
    image: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - web
    restart: always
  jnginx:
    build: ./jnginx
    depends_on:
      - web
    volumes:
      - .:/code
    ports:
      - "80:80"
    networks:
      - web
    restart: always
networks:
  web:
