version: '2'
services:
  db:
    image: postgres
    volumes:
      - "/etc/postgresql"
      - "/var/log/postgresql"
      - "/var/lib/postgresql"
    networks:
      - web
  web:
    build: .
    image: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - web
  jnginx:
    build: ./jnginx
    depends_on:
      - web
      - db
    volumes:
      - .:/code
    ports:
      - "80:80"
    networks:
      - web
networks:
  web:
